#!/bin/bash
mkdir -p good_bins/
gcc -DDEBUG -g -Wall -lportaudio -lrt -lm -lasound -ljack -pthread -lglut -lGL -lGLU kaleidosynth.c kiss_fftr.c kiss_fft.c -o bin/kaleidosynth && \
  bin/kaleidosynth #cp ./bin/kaleidosynth good_bins/kaleidosynth.$(openssl rand -base64 3)
