#!/bin/bash
mkdir -p good_bins/
gcc -DDEBUG -g -Wall -l portaudio -lrt -lm -lasound -ljack -pthread kaleidosynth.c kiss_fftr.c kiss_fft.c -o bin/kaleidosynth && \
  cp ./bin/kaleidosynth good_bins/kaleidosynth.$(openssl rand -base64 3)
