#!/bin/bash
mkdir -p good_bins/ bin/
gcc -DDEBUG -g -Wall \
  -I /System/Library/Frameworks/OpenGL.framework/Headers \
  -I /usr/local/opt/openblas/include \
  -L /usr/local/opt/openblas/lib \
  -lportaudio -lm  -pthread -framework OpenGL -framework GLUT -framework Accelerate \
  kaleidosynth.c kiss_fftr.c kiss_fft.c  \
  -o bin/kaleidosynth && \
  (killall kaleidosynth ; OMP_NUM_THREADS=6 bin/kaleidosynth) 
